import { PARTNER_CODES } from '../domain/constants.js'
import type { FormFieldDefinition } from './types.js'

export const MONTHLY_REPORT_FORM_DEFS: FormFieldDefinition[] = [
  // Identity
  {
    path: 'identity.pcCode',
    label: 'Mã Điện lực',
    section: 'Thông tin chung',
    inputType: 'text',
    isRequired: true,
    displayOrder: 1,
    isReadOnly: true,
    isDerivedFromContext: true,
    widthHint: 'w-32',
  },
  {
    path: 'identity.pcName',
    label: 'Tên Điện lực',
    section: 'Thông tin chung',
    inputType: 'text',
    isRequired: true,
    displayOrder: 2,
    isReadOnly: true,
    isDerivedFromContext: true,
    widthHint: 'w-48',
  },

  // General
  {
    path: 'general.partnerCode',
    label: 'Đối tác',
    section: 'Thông tin chung',
    inputType: 'select',
    isRequired: true,
    displayOrder: 3,
    options: PARTNER_CODES,
    widthHint: 'w-40',
  },
  {
    path: 'general.contactPerson',
    label: 'Người liên hệ',
    section: 'Thông tin chung',
    inputType: 'text',
    isRequired: false,
    displayOrder: 4,
    widthHint: 'w-40',
  },
  {
    path: 'general.contactPhone',
    label: 'Điện thoại',
    section: 'Thông tin chung',
    inputType: 'text',
    isRequired: false,
    displayOrder: 5,
    widthHint: 'w-32',
  },

  // Contract
  {
    path: 'contract.contractNumber',
    label: 'Số hợp đồng',
    section: 'Hợp đồng',
    inputType: 'text',
    isRequired: true,
    displayOrder: 6,
    widthHint: 'w-40',
  },
  {
    path: 'contract.signedDate',
    label: 'Ngày ký',
    section: 'Hợp đồng',
    inputType: 'date',
    isRequired: false,
    displayOrder: 7,
    widthHint: 'w-32',
  },
  {
    path: 'contract.validUntil',
    label: 'Ngày hết hạn',
    section: 'Hợp đồng',
    inputType: 'date',
    isRequired: false,
    displayOrder: 8,
    widthHint: 'w-32',
  },

  // Execution (Year Keyed Expansion Fields)
  {
    path: 'execution.[year].planned',
    label: 'Kế hoạch',
    section: 'Thực hiện',
    inputType: 'number',
    isRequired: true,
    displayOrder: 9,
    isYearKeyed: true,
    widthHint: 'w-32',
  },
  {
    path: 'execution.[year].actual',
    label: 'Thực tế',
    section: 'Thực hiện',
    inputType: 'number',
    isRequired: true,
    displayOrder: 10,
    isYearKeyed: true,
    widthHint: 'w-32',
  },
  {
    path: 'execution.[year].completionPercentage',
    label: 'Tỷ lệ HT (%)',
    section: 'Thực hiện',
    inputType: 'number',
    isRequired: false,
    displayOrder: 11,
    isYearKeyed: true,
    widthHint: 'w-24',
  },

  // Pole Quantities
  {
    path: 'poleQuantities.totalPoles',
    label: 'Tổng số cột',
    section: 'Số lượng cột',
    inputType: 'number',
    isRequired: true,
    displayOrder: 12,
    widthHint: 'w-32',
  },
  {
    path: 'poleQuantities.sharedPoles',
    label: 'Số cột dùng chung',
    section: 'Số lượng cột',
    inputType: 'number',
    isRequired: false,
    displayOrder: 13,
    widthHint: 'w-32',
  },
  {
    path: 'poleQuantities.newlyAdded',
    label: 'Cột phát sinh mới',
    section: 'Số lượng cột',
    inputType: 'number',
    isRequired: false,
    displayOrder: 14,
    widthHint: 'w-32',
  },

  // Revenue
  {
    path: 'revenueResult.expectedRevenue',
    label: 'Doanh thu dự kiến',
    section: 'Doanh thu',
    inputType: 'currency',
    isRequired: true,
    displayOrder: 15,
    widthHint: 'w-40',
  },
  {
    path: 'revenueResult.actualCollected',
    label: 'Thực thu',
    section: 'Doanh thu',
    inputType: 'currency',
    isRequired: true,
    displayOrder: 16,
    widthHint: 'w-40',
  },

  // Debt
  {
    path: 'debtAnalysis.totalDebt',
    label: 'Tổng công nợ',
    section: 'Công nợ',
    inputType: 'currency',
    isRequired: true,
    displayOrder: 17,
    widthHint: 'w-40',
  },
  {
    path: 'debtAnalysis.overdueDebt',
    label: 'Nợ quá hạn',
    section: 'Công nợ',
    inputType: 'currency',
    isRequired: true,
    displayOrder: 18,
    widthHint: 'w-40',
  },
  {
    path: 'debtAnalysis.debtClassification',
    label: 'Phân loại nợ',
    section: 'Công nợ',
    inputType: 'select',
    isRequired: false,
    displayOrder: 19,
    options: ['SAFE', 'WARNING', 'CRITICAL'],
    widthHint: 'w-32',
  },

  // Notes
  {
    path: 'notes',
    label: 'Ghi chú',
    section: 'Ghi chú',
    inputType: 'text',
    isRequired: false,
    displayOrder: 20,
    widthHint: 'w-64',
  },
]
