import type { FormFieldDefinition } from './types.js'

export const MONTHLY_REPORT_FORM_DEFS: FormFieldDefinition[] = [
  {
    path: 'general.doi_tac',
    label: 'ĐỐI TÁC',
    section: 'THÔNG TIN CHUNG',
    inputType: 'select',
    isRequired: true,
    displayOrder: 1,
    options: [
      'VNPT',
      'FPT',
      'MOBI',
      'SCTV',
      'VTVCAB',
      'VNMOBILE',
      'CMC',
      'HTC',
      'ACT',
      'TPCOMS',
      'TTVT KVII',
      'TIVICOM',
      'NETNAM',
      'HAILONG',
      'HTV',
      'TANVIETSINH',
      'HTMMN',
      'KHOINGHIEP',
      'STC',
      'HUNGMANH',
      'VIETTHANH',
      'KHAC',
    ],
    widthHint: 'w-40',
  },
  {
    path: 'contract.so_hd_phu_luc_hop_dong',
    label: 'SỐ HĐ/PHỤ LỤC HỢP ĐỒNG',
    section: 'HỢP ĐỒNG',
    inputType: 'text',
    isRequired: true,
    displayOrder: 2,
    widthHint: 'w-40',
  },
  {
    path: 'contract.ngay_ky_hd_plhd',
    label: 'NGÀY KÝ HĐ/PLHĐ',
    section: 'HỢP ĐỒNG',
    inputType: 'date',
    isRequired: true,
    displayOrder: 3,
    widthHint: 'w-32',
  },
  {
    path: 'contract.hieu_luc_den',
    label: 'HIỆU LỰC ĐẾN',
    section: 'HỢP ĐỒNG',
    inputType: 'date',
    isRequired: true,
    displayOrder: 4,
    widthHint: 'w-32',
  },
  {
    path: 'contract.gia_tri_hop_dong_nam',
    label: 'Giá trị hợp đồng năm (Không bao gồm thuế VAT)',
    section: 'HỢP ĐỒNG',
    inputType: 'currency',
    isRequired: true,
    displayOrder: 5,
    widthHint: 'w-40',
  },
  {
    path: 'execution.opening_balance_by_year.2023',
    label: 'Tồn đầu kỳ 2023',
    section: 'TÌNH HÌNH THỰC HIỆN',
    inputType: 'number',
    isRequired: true,
    displayOrder: 6,
    widthHint: 'w-32',
  },
  {
    path: 'execution.opening_balance_by_year.2024',
    label: 'Tồn đầu kỳ năm 2024',
    section: 'TÌNH HÌNH THỰC HIỆN',
    inputType: 'number',
    isRequired: true,
    displayOrder: 7,
    widthHint: 'w-32',
  },
  {
    path: 'execution.opening_balance_by_year.2025',
    label: 'Tồn đầu kỳ năm 2025',
    section: 'TÌNH HÌNH THỰC HIỆN',
    inputType: 'number',
    isRequired: true,
    displayOrder: 8,
    widthHint: 'w-32',
  },
  {
    path: 'execution.generated_by_year.[year]',
    label: 'Doanh số phát sinh trong kỳ (bao gồm thuế VAT)',
    section: 'TÌNH HÌNH THỰC HIỆN',
    inputType: 'number',
    isRequired: true,
    displayOrder: 9,
    isYearKeyed: true,
    widthHint: 'w-40',
  },
  {
    path: 'execution.collected_by_year.2023',
    label: 'Đã thu trong kỳ 2023',
    section: 'TÌNH HÌNH THỰC HIỆN',
    inputType: 'number',
    isRequired: true,
    displayOrder: 10,
    widthHint: 'w-32',
  },
  {
    path: 'execution.collected_by_year.2024',
    label: 'Đã thu trong kỳ năm 2024',
    section: 'TÌNH HÌNH THỰC HIỆN',
    inputType: 'number',
    isRequired: true,
    displayOrder: 11,
    widthHint: 'w-32',
  },
  {
    path: 'execution.collected_by_year.2025',
    label: 'Đã thu trong kỳ năm 2025',
    section: 'TÌNH HÌNH THỰC HIỆN',
    inputType: 'number',
    isRequired: true,
    displayOrder: 12,
    widthHint: 'w-32',
  },
  {
    path: 'execution.closing_balance',
    label: 'Tồn cuối kỳ (bao gồm thuế VAT)',
    section: 'TÌNH HÌNH THỰC HIỆN',
    inputType: 'number',
    isRequired: true,
    displayOrder: 13,
    widthHint: 'w-40',
  },
  {
    path: 'pole_quantities.duoi_8_5m',
    label: 'Dưới 8.5m',
    section: 'SỐ LƯỢNG CỘT ĐIỆN',
    inputType: 'number',
    isRequired: true,
    displayOrder: 14,
    widthHint: 'w-32',
  },
  {
    path: 'pole_quantities.tu_8_5_den_10_5m',
    label: 'Từ 8.5 đến 10.5m',
    section: 'SỐ LƯỢNG CỘT ĐIỆN',
    inputType: 'number',
    isRequired: true,
    displayOrder: 15,
    widthHint: 'w-32',
  },
  {
    path: 'pole_quantities.tu_10_5_den_12_5m',
    label: 'Từ 10.5 đến 12.5m',
    section: 'SỐ LƯỢNG CỘT ĐIỆN',
    inputType: 'number',
    isRequired: true,
    displayOrder: 16,
    widthHint: 'w-32',
  },
  {
    path: 'pole_quantities.tren_12_5m',
    label: 'Trên 12.5m',
    section: 'SỐ LƯỢNG CỘT ĐIỆN',
    inputType: 'number',
    isRequired: true,
    displayOrder: 17,
    widthHint: 'w-32',
  },
  {
    path: 'revenue_result.doanh_thu_thuc_hien_nam',
    label: 'Doanh thu thực hiện (chưa VAT)',
    section: 'DOANH THU',
    inputType: 'currency',
    isRequired: true,
    displayOrder: 18,
    widthHint: 'w-40',
  },
  {
    path: 'revenue_result.ti_le_thuc_hien',
    label: 'Tỉ lệ thực hiện',
    section: 'DOANH THU',
    inputType: 'number',
    isRequired: true,
    displayOrder: 19,
    widthHint: 'w-32',
  },
  {
    path: 'debt_analysis.duoi_6_thang',
    label: 'Dưới 6 tháng',
    section: 'PHÂN TÍCH NỢ',
    inputType: 'number',
    isRequired: true,
    displayOrder: 20,
    widthHint: 'w-40',
  },
  {
    path: 'debt_analysis.tu_6_den_duoi_12_thang',
    label: '6 đến dưới 12 tháng',
    section: 'PHÂN TÍCH NỢ',
    inputType: 'number',
    isRequired: true,
    displayOrder: 21,
    widthHint: 'w-40',
  },
  {
    path: 'debt_analysis.tu_12_den_duoi_24_thang',
    label: '12 đến dưới 24 tháng',
    section: 'PHÂN TÍCH NỢ',
    inputType: 'number',
    isRequired: true,
    displayOrder: 22,
    widthHint: 'w-40',
  },
  {
    path: 'debt_analysis.tu_24_den_duoi_36_thang',
    label: '24 đến dưới 36 tháng',
    section: 'PHÂN TÍCH NỢ',
    inputType: 'number',
    isRequired: true,
    displayOrder: 23,
    widthHint: 'w-40',
  },
  {
    path: 'debt_analysis.tren_36_thang',
    label: 'Trên 36 tháng',
    section: 'PHÂN TÍCH NỢ',
    inputType: 'number',
    isRequired: true,
    displayOrder: 24,
    widthHint: 'w-40',
  },
  {
    path: 'notes.ghi_chu',
    label: 'Ghi chú',
    section: 'GHI CHÚ',
    inputType: 'text',
    isRequired: false,
    displayOrder: 25,
    widthHint: 'w-64',
  },
]
